CREATE TABLE TransactionAudit (

    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionDate DATE

);
CREATE OR REPLACE TRIGGER trg_transaction_audit
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN

    INSERT INTO TransactionAudit(
        TransactionID,
        AccountID,
        Amount,
        TransactionDate
    )
    VALUES(
        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.Amount,
        SYSDATE
    );

END;
/
INSERT INTO Transactions
VALUES(
    101,
    1,
    SYSDATE,
    1000,
    'Deposit'
);

COMMIT;
SELECT *
FROM TransactionAudit;